stage_1:
  target: stage1.RAE
  params:
    encoder_cls: 'CRadiov4withNorm'
    encoder_config_path: '/root/paddlejob/workspace/env_run/penghaotian/models/C-RADIOv4/C-RADIOv4-SO400M'
    encoder_input_size: 256
    encoder_params:
      radio_path: '/root/paddlejob/workspace/env_run/penghaotian/models/C-RADIOv4/C-RADIOv4-SO400M'
      input_size: 256
    decoder_config_path: 'configs/decoder/ViTXL'
    decoder_patch_size: 16
    pretrained_decoder_path: 'models/decoders/cradio/SO400M/ViTXL/model.pt'
    noise_tau: 0.0
    reshape_to_2d: true
    normalization_stat_path: 'models/stats/cradio/SO400M/imagenet1k/normalization_stats.pt'

stage_2:
  target: stage2.models.DDT.DiTwDDTHead
  params:
    input_size: 16
    patch_size: 1
    in_channels: 1152
    hidden_size: [1152, 2048]
    depth: [28, 2]
    num_heads: [16, 16]
    mlp_ratio: 4.0
    class_dropout_prob: 0.1
    num_classes: 1000
    use_qknorm: false
    use_swiglu: true
    use_rope: true
    use_rmsnorm: true
    wo_shift: false
    use_pos_embed: true

transport:
  params:
    path_type: 'Linear'
    prediction: 'velocity'
    loss_weight: null
    time_dist_type: 'logit-normal_0_1'

sampler:
  mode: ODE
  params:
    sampling_method: 'euler'
    num_steps: 50
    atol: 1.0e-6
    rtol: 1.0e-3
    reverse: false

guidance:
  method: 'cfg'
  scale: 1.0
  t_min: 0.0
  t_max: 1.0

misc:
  latent_size: [1152, 16, 16] # [C, H, W]  SO400M embed_dim=1152, 256/16=16 tokens
  num_classes: 1000
  time_dist_shift_dim: 294912 # 16*16*1152
  time_dist_shift_base: 4096

eval:
  eval_interval: 25000
  eval_model: true
  data_path: '/root/paddlejob/workspace/env_run/penghaotian/datas/imagenet-1k/validation'
  reference_npz_path: '/root/paddlejob/workspace/env_run/penghaotian/datas/imagenet-1k/val_256_ref_stats.npz'

training:
  epochs: 1400
  global_batch_size: 1024   # effective bs=1024; micro_bs = 1024/(2GPU*4accum) = 128/GPU
  grad_accum_steps: 4       # reduce per-step memory: 128/GPU instead of 512/GPU
  ema_decay: 0.9995
  num_workers: 16
  log_interval: 100
  checkpoint_interval: 10
  sample_every: 10000
  clip_grad: 1.0
  global_seed: 42
  optimizer:
    lr: 2.0e-4
    betas: [0.9, 0.95]
    weight_decay: 0.0
  scheduler:
    type: linear
    warmup_epochs: 40
    decay_end_epoch: 800
    base_lr: 2.0e-4
    final_lr: 2.0e-5
    warmup_from_zero: false
